// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcsBb2Rt1OLUVn9y04W4Ikj_89quxivPQ',
    appId: '1:480780627365:web:23abb6ed39f34fb7b0cc4c',
    messagingSenderId: '480780627365',
    projectId: 'wallet-158696',
    authDomain: 'wallet-158696.firebaseapp.com',
    storageBucket: 'wallet-158696.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGWshN__aI2jjOa0AqK8mi0O-9WRW3_Yc',
    appId: '1:480780627365:android:1f5fa055317aab9ab0cc4c',
    messagingSenderId: '480780627365',
    projectId: 'wallet-158696',
    storageBucket: 'wallet-158696.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNBbmV5npJglp-xO7y2vKBkuc0fAfrVkM',
    appId: '1:480780627365:ios:789c5cd986b5cc68b0cc4c',
    messagingSenderId: '480780627365',
    projectId: 'wallet-158696',
    storageBucket: 'wallet-158696.appspot.com',
    iosClientId: '480780627365-tih11mmdv86bc5mupasr40sbmkiog4c8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNBbmV5npJglp-xO7y2vKBkuc0fAfrVkM',
    appId: '1:480780627365:ios:7d4a5f34316b6c88b0cc4c',
    messagingSenderId: '480780627365',
    projectId: 'wallet-158696',
    storageBucket: 'wallet-158696.appspot.com',
    iosClientId: '480780627365-mgfbjb2d467idn3a23kbv4rgog4cc0no.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallet.RunnerTests',
  );
}
